### ISSUE TITLE
Auto cast numeric parameters as integers

### ISSUE THREAD

**Issue by haggen** [molefrog/wouter#28] opened 2019-05-17 21:08 UTC
Here's an idea:

Cast parameters as integers when it can, leave it otherwise.

**Use case**: I'm comparing `match.id` with `object.id` to apply a `selected` class and it would be great  to not have to use `==` and not have to cast it myself. 

**Why**: I don't see casting parameter types inside the scope of my application, but rather belonging to the routing mechanism.

**How would I do**: test each parameter value for a _string of numbers_  and apply `parseInt` accordingly.

I can hack it together and send a PR if you like it. Also, let me know if think another approach would be best.

Cheers! :beer:

**Comment by Paratron** [comment] 2019-05-19 06:44
Usually, IDs are strings, not integers. What you basically demand is, that because you chose to use numeric IDs, the router should handle the conversion for you.

URL parameters are automatically extracted parts of an URL - which is a string. The router should not change that and make any assumptions about your code. The next project breaks because of that change, because they assumed to receive strings instead of numbers.

I would suggest to leave the mechanic as-is and do any conversion on your side; if its even needed.

**Comment by molefrog** [comment] 2019-05-19 09:56
I agree with @Paratron, if we decide to convert these parameters automatically, this might create a non-obvious behaviour, when for example the parameter was intended to be a string, but in some rare cases it will be converted to integer. 

There was a similar thread in React Router and seems like they have decided to avoid this possible complexity https://github.com/ReactTraining/react-router/issues/6097. Ideally this can be solved with types, by IMO the design of the library becomes too overloaded.

Even in Rails which was designed to be intuitive and convention-based they don't provide an automatic conversion. What they do instead is following:
```ruby
def show
  user_id = params[:id] # this is a string

  # but this works fine, since ActiveRecord#find accepts both strings and integers
  user = User.find(user_id)
end
```

@haggen But if you still want to have this in your project really bad I would suggest overriding a default matcher function like this:

```js
import { Route } from "wouter";
import makeMatcher from "wouter/matcher";

const autoCastIntegers = (objectOrNull) => {
   ...
}

const matcherWithTransformedParams = (transformFn) => {
  const originalMatcher = makeMatcher();

  return (pattern, path) => {
    const [match, params] = originalMatcher(pattern, path);
    return [match, transformFn(params)]
  }
}

<Router matcher={matcherWithTransformedParams(autoCastIntegers)}>
  ...
</Router>
```

Thanks for suggesting this feature, but we are likely not going to implement this. Closing the issue.

**Closed by molefrog** 2019-05-19 09:56 UTC
