### ISSUE TITLE
Relative routes and links: provide demo in README

### ISSUE THREAD

**Issue by kristiandupont** [molefrog/wouter#47] opened 2019-07-09 08:47 UTC
This looks neat!

Does it support relative links and routes like Reach Router?

**Comment by molefrog** [comment] 2019-07-09 08:53
@kristiandupont Hey! Thanks for the feedback!
So by relative links do you mean something like an app mounted at the static subpath, so all the routes cointain the fixed prefix?

Like */users/1* actually goes to _**/app**/users/1_?

**Comment by kristiandupont** [comment] 2019-07-09 09:07
Yes. See: https://reach.tech/router/example/nested-routes

**Comment by midudev** [comment] 2019-07-09 10:14
Interested as well. Implementation example from react-router v.3

```
    <Route path="/:lang" component={RealEstateApp}>
      <Route
        path="catalogo-productos"
        component={loadUserProductCataloguePage}
      />
   </Route>
```

**Comment by molefrog** [comment] 2019-07-09 13:38
Unfortunately, nested routing isn't something that is supported at the moment and it isn't in the roadmap either. This would probably require the reimplementation of the entire library, however I do believe that you can achieve the similar behaviour by extending the default `Route` component. It might also require some `useContext` magic. 

I tried to recreate this in CodeSandbox, it's not 100% working, but at least the idea:
https://codesandbox.io/s/wouter-nested-routes-ffd5h

**Comment by molefrog** [comment] 2019-07-09 13:41
The main problem is: wouter matches an entire url string by default, so the parent route won't be rendered. I can suggest to see how this can be implemented in React Router first, as it was the main source of the inspiration in terms of an API.

**Comment by molefrog** [comment] 2019-07-23 09:12
Hey sorry guys, I don't think this ever will be implemented in the library. Having nesting routes seems like something that is way too beyond wouter's mission. 

I do think, however, that it should be possible to write a library that implements this using wouter's standard components like `Route` or hooks like `useLocation`. I'll be glad to reference this in the library README if someone write this packages.

Closing this 😢

**Comment by Hotell** [comment] 2019-12-06 10:07
> Hey sorry guys, I don't think this ever will be implemented in the library. Having nesting routes seems like something that is way too beyond wouter's mission.
>
> I do think, however, that it should be possible to write a library that implements this using wouter's standard components like `Route` or hooks like `useLocation`. I'll be glad to reference this in the library's README if someone write this packages.
>
> Closing this 😢

I'd suggest to put this in main Readme. as for a person coming from other common routing solutions, one would expect that following works 👉

```jsx
const App = () => {
  return (
    <Switch>
      <Route path="/">
        <Home />
      </Route>
      <Route path="/topics">
        <Topics />
      </Route>
    </Switch>
  );
};

const Topics = () => {
  return (
    <Switch>
      <Route path="/topics">
        <h3>Please select a topic.</h3>
      </Route>
      <Route path="/topics/:topicId">
        <Topic />
      </Route>
    </Switch>
  );
};
```

WDYT ? thx

**Comment by molefrog** [comment] 2019-12-09 13:43
@Hotell Hey! Actually, with the latest basepath update it's now possible to use nested routes! I'll compile a demo and put it in the README

**Comment by Hotell** [comment] 2019-12-09 14:13
wooot! looking forward to it 👌

**Comment by Hotell** [comment] 2019-12-18 12:01
> @Hotell Hey! Actually, with the latest basepath update it's now possible to use nested routes! I'll compile a demo and put it in the README

@molefrog  any news ? 🙏 Can I help in some way ?

**Comment by cztomsik** [comment] 2019-12-21 11:05
It is kinda possible (you need to wrap routes in the `<Router base="...">`) but it's not exactly what you might expect, because `<Router>` is not relative (does not respect base of its parent)

Not sure if this is by design but I think it could be fixed.

**Comment by molefrog** [comment] 2020-07-19 11:17
Documented in the README:
https://github.com/molefrog/wouter#how-do-i-make-a-default-route

**Closed by molefrog** 2020-07-19 11:17 UTC
