### ISSUE TITLE
Router base is key sensitive?

### ISSUE THREAD

**Issue by Veranete** [molefrog/wouter#133] opened 2020-10-13 16:59 UTC
Hi,

The Router base="/easy/pd" not match for instance with http://mysite/Easy/PD, is keysensitive? is posible that by default keysensitive=false, if not, how can I implement a match not keysensitive?

Thanks ...

**Comment by molefrog** [comment] 2020-10-14 13:02
@Veranete I can confirm that the `base` is case-sensitive, which is confusing because the rest of the path isn't. Pretty sure we can fix that by tweaking https://github.com/molefrog/wouter/blob/2a9d07f3184e7c549a7269c1344c1d4fa4d5a56b/use-location.js#L78 function.

I'll mark this issue as a good first issue for anyone who would like to contribute.

**Comment by molefrog** [comment] 2020-10-22 09:19
Thanks to @cbbfcd, this has been fixed in the latest release:
v2.5.2 https://github.com/molefrog/wouter/releases/tag/v2.5.2

**Closed by molefrog** 2020-10-22 09:19 UTC
Labels: good first issue
