### ISSUE TITLE
setLocation not redirecting

### ISSUE THREAD

**Issue by kaioduarte** [molefrog/wouter#72] opened 2019-08-10 22:18 UTC
I'm checking if a param was provided, otherwise I redirect to login page, but it's not working when the `setLocation` is inside a `useState`, I tried within a `useEffect` and `setTimeout` and it works properly.

Demo: https://codesandbox.io/s/wouter-setlocation-bug-039o1

**Comment by ifokeev** [comment] 2019-08-12 06:46
use `useEffect`. I think it's an antipattern of using `useState`

**Comment by molefrog** [comment] 2019-08-12 11:16
Hi @kaioduart!

As @ifokeev pointed out the issue is most probably in invoking a redirect inside of `useState` callback. You should consider using `useEffect` instead:

```js
const extractedId = params && params.id

useEffect(() => {
    // this will only be called when `extractedId` changes
    if (!extractedId) {
      setLocation("/login");
    }
}, [extractedId]);
```

Also, not sure what kind of logic you're trying to achieve here, but my guess is that you want to redirect logged out users to the login page. For that I can recommend to save the current authorization status `loggedIn: true / false` somewhere in the app tree, and then have this logic at the top-level component:

```js
// this component ensures that logged out users are always redirected to the login page
// Wrap your app with this component
const AuthorizationGuard = props => {
  const isLoggedIn = useContext(LoggedInContext);
  const [currentPage, navigate] = useLocation();

  useEffect(() => {
    if (!isLoggedIn && currentPage !== '/login') {
      navigate('/login');
    }
  }, [isLoggedIn, currentPage]);

  return props.children;
}
```

**Comment by molefrog** [comment] 2019-08-12 11:16
Closing this, as it seems more like a misuse of the library, rather than a bug.

**Closed by molefrog** 2019-08-12 11:16 UTC
