### ISSUE TITLE
v3.0.0-rc.1: When use hash router,  Ctrl+click on <Link>, new window is opened with wrong url

### ISSUE THREAD

**Issue by fuchen** [molefrog/wouter#392] opened 2023-11-30 16:12 UTC
3.0.0-rc.1

```
<Router hook={useHashLocation}>
  <Link to="/abc">link text</Link>
</Router>
```
Click the link, windows location is changed to `https://example.com/#/abc` as expected.
Ctrl+click, a new tab is opened at `https://example.com/abc#/abc`

**Comment by molefrog** [comment] 2023-12-01 08:31
Yeah, that is a long known problem that we don't have a solution for yet. This might be a duplicate of https://github.com/molefrog/wouter/issues/215, could you take a look?

**Comment by fuchen** [comment] 2023-12-01 12:06
I use following code to work around:
```
const HashLink = ({ to, children }: { to: string, children: React.ReactNode }) => {
  return (
    <a href={'#' + to}>
      {children}
    </a>
  )
}
```
Seems that the problem is we cannot get the composed URL with current `useLocation` API.

**Closed** 2024-03-11 09:59 UTC
Labels: feature, V3
