### ISSUE TITLE
IIS lost part of url

### ISSUE THREAD

**Issue by Veranete** [molefrog/wouter#128] opened 2020-07-29 22:39 UTC
Hi, 

First, thanks for it, really is usefull

Second, When I publish the app on IIS server, the fisrt request run fine, but, when I navigate, the url lost part, i.e: I publish in https://mywebserver/groupapps/specificapp/Home when I click change the url to https://mywebserver/Home; work fine but lost part url; any idea

Thanks .........

**Comment by molefrog** [comment] 2020-07-30 07:01
@Veranete Hi! I assume that your app is mounted at `/groupapps/specificapp/`, right? Did you try adding a base parameter to the Router: https://github.com/molefrog/wouter#i-deploy-my-app-to-the-subfolder-can-i-specify-a-base-path

In your case the Router should look like `<Router base="/groupapps/specificapp/">`.

**Comment by molefrog** [comment] 2020-08-03 07:18
The issue is probably related to the base path misconfiguration. I'm going to close this for now, but feel free to reopen if it doesn't solve your problem.

**Closed by molefrog** 2020-08-03 07:18 UTC

**Comment by Veranete** [comment] 2020-08-09 21:48
Thanks for your time, your answer resolved the behavior
