### ISSUE TITLE
Send the state object with navigate or setLocation

### ISSUE THREAD

**Issue by kripashank** [molefrog/wouter#342] opened 2023-09-19 15:27 UTC
HI ,

Can anyone suggest how to send the state with the useLocation or navigate in wouter?,

Something like below in react router,

For sending:

navigate("/success", {
          state: {
            stripeData: res.data,
            products: cart,
          },
        });

For Receiving:

import { useLocation } from "react-router-dom";
  const location = useLocation();
  const data = location.state.stripeData;
  const cart = location.state.products;

**Comment by molefrog** [comment] 2023-10-09 18:13
There is some work being done in #325, but we are also working on the next major release where this feature has already been implemented. See https://github.com/molefrog/wouter/pull/349

Also, this seems to be a duplicate of #316

**Closed by molefrog** 2023-10-09 18:13 UTC
Labels: V3
