### ISSUE TITLE
[question] Parent route layout (<Outlet />)

### ISSUE THREAD

**Issue by gius** [molefrog/wouter#242] opened 2022-04-10 07:49 UTC
I was not able to figure that out from the documentation. How do you handle a scenario when a parent route should render some layout with a child route inside? Similar to [React Router's Outlet](https://reactrouter.com/docs/en/v6/api#outlet).

**Comment by molefrog** [comment] 2022-04-11 06:59
Hi! It's currently not provided out of the box, however implementing `<Outlet />` functionality shouldn't be hard. I'll try to come up with an example to illustrate my point.

**Comment by gius** [comment] 2022-04-11 07:48
Thank you! Basically, it should be enough to figure out if a route is a parent of the current path. 

E.g., that `/finance` and `/finance/orders` are parents of the current `/finance/orders/123` path.

**Comment by PodaruDragos** [comment] 2022-10-14 11:21
this would be such a good feature to have built in. looking forward to the example @molefrog

**Comment by HansBrende** [comment] 2022-11-04 04:33
@gius @molefrog Here's an example of how this could be achieved out of the box without any "Outlet" (hint: React has its own built-in "outlet" called `children`). To reproduce the linked react-router example exactly (barring any silly coding mistakes I've made here since I did this off the cuff in about 30 seconds):

```typescript
function Dashboard({children}: React.PropsWithChildren<{}>) {
  return (
    <div>
      <h1>Dashboard</h1>
      {children}
    </div>
  );
}

function App() {
  return (
      <Route path="/">
          <Dashboard>
              <Route path="/messages"> // could also use a <Switch> here
                  <DashboardMessages/>
              </Route>
              <Route path="/tasks">
                  <DashboardTasks/>
              </Route>
          </Dashboard>
      </Route>
  );
}
```

There is literally no need for `Outlet` as far as I can tell. I always thought that was a pointless addition to react-router. Try as I might, I've never been able to come up with one single good explanation for why `Outlet` is necessary or desirable. Only serves to make function components less readable and entirely un-reusable outside of an outlet context (as well as adding the extra overhead of those gazillion `useContext` calls).

**Comment by molefrog** [comment] 2022-11-05 15:16
I absolutely agree with @HansBrende, seems like outlets can be easily replaced with components. I understand why it is present in react-router: outlets can be found in some frameworks like Ember or Rails, so some devs might be familiar with this pattern.

I believe that wouter should not go down that route (pun intended), otherwise there is a risk of becoming 1-1 clone of react router. I like to compare it to Preact vs React. While Preact in its core has similar API as React, it does however leave aside some additional things like portals.

I'm closing this issue, thank you all for participating in this discussion.

**Closed by molefrog** 2022-11-05 15:16 UTC
