### ISSUE TITLE
Add TypeScript type definitions to wouter-types repo, publish to definitely-typed

### ISSUE THREAD

**Issue by mcongy** [molefrog/wouter#5] opened 2019-04-16 22:04 UTC
Hello,

After 4 years of using React, I finally see a reasonable react-router.

There's just one thing I'd appreciate.

Could you please provide typescript type definitions? Either include it in this package, or add them to definitely-typed repo.

Thank you!

**Comment by molefrog** [comment] 2019-04-17 09:08
Alright, a few people have already been asking about the TS types. I've never worked with TS before, but I think I get the idea: we could add an `index.d.ts` file to the package with type declarations. This is definitely something I'll need a help with. I'm going to add a "Help Needed" tag to this issue, so if someone wants to contribute this might be a good place to start.

**Comment by Paratron** [comment] 2019-04-17 11:17
Be careful with typings if your project is not written in typescript and you do not plan to use it in a TS project any time. The problem is that if your typings are not up to date with your project code, you will have bugs in here that you cant/wont fix on your own. This hinders development greatly.

I would keep typings out of any project that is not TS based. Creating a separate project for types (or have it managed in definitely typed) is a good way to get started.

**Comment by nksfrank** [comment] 2019-04-20 06:03
Perhaps adding the typings to the larger typings library where contributors can maintain it?

**Comment by molefrog** [comment] 2019-04-24 10:13
Ok, so I checked the TypeScript docs, and seems like adding types to `definitely-typed` is the most appropriate option. One thing I don't quite understand yet is how do I make sure the types correspond to the latest version of the library? Let's say I publish a new version to NPM, how do I make sure types in the repo are up to date?

Hope anyone could help me with that. Thanks!

**Comment by Paratron** [comment] 2019-04-24 10:29
Well, you would need to update the typings before you publish, or have somebody update them.

**Comment by nksfrank** [comment] 2019-04-24 11:29
You match version number on typings package with this lib version number
and it should work out fine

**Comment by Paratron** [comment] 2019-04-24 11:30
And how does this solve the problem that would not be available for the recent version?

**Comment by nksfrank** [comment] 2019-04-24 12:08
In that case it wouldn't. But it would signal TS users that they shouldn't
upgrade yet.

Could a possibility be having a .d.ts file in the root of this repo. And
keep it updated between releases?

**Comment by Paratron** [comment] 2019-04-24 12:10
This brings us back to my comment from above. If the author is not using TS for this project, it doesnt make sense to maintain typings here, since he would get the bugs assigned in this project and cannot take care of them. ¯\_(ツ)_/¯

**Comment by yurist38** [comment] 2019-04-26 17:32
Hey guys! I see quite a lot of people are interested in TS support. I think I could migrate it to TS and open a PR for that. @molefrog How do you feel about going to TS?

**Comment by Paratron** [comment] 2019-04-27 11:39
I would leave the migration to the author - if he even wants to. What does it help if its typed afterwards but he cannot maintain it anyore? :)

Seriously - the only sane way is putting types on definitely typed. And somebody who cares about TS needs to maintain it. Forever. If thats not possible, drop the idea completely.

**Comment by molefrog** [comment] 2019-04-27 11:58
Hey, @yurist38 I appreciate the enthusiasm, but I must say I kinda agree with @Paratron and don't think rewriting the entire library in TS is a wise decision. 

When I was designing the library I wanted it to be as minimal as possible (no deps, no transpilation). That's said I intentionally left out some features from React Router, just to make it cover 95% of use cases. Rewriting it in TS would add some complexity that I really think we would benefit from. 

Again, sorry for rejecting this, but what you can help with however is creating contributing to https://github.com/molefrog/wouter-types by adding `index.d.ts` and later publishing it to definitely-typed. This is what I would need help with, since I'm not that familiar with TS world yet.

**Comment by yurist38** [comment] 2019-04-27 12:13
I don't really see a point why you are so scared by migrating to TS but no problem, it's completely up to you though.

**Comment by molefrog** [comment] 2019-04-27 18:43
This might not be the best explanation, but I just thought I should share this just to explain why exactly I'm leaning towards having everything in js. I have this little mental conflict in my head 🙈: 

I'm afraid of having a *transpilation stage*. This whole library was sort of an experiment around an idea that we can easily publish modern frontend libraries as-is, no babel, no transpilation, just plain ES6 (that's right) modules. An ES6 (ex ES2015) is currently fully supported by the majority of browsers, so ideally it should be up to a library consumer to decide whether or not this should be transpiled. That being said, if someone wants to support IE11 in their project, they should be aware that the transpilation stage needs to be enabled for `node_modules` as well. I should probably let people know in advance before they start using the library about this approach in the README.

So I know it's not entirely related, but having ts source will force us to introduce the transpilation (ts -> js) before publishing, and this just kinda breaks the concept 😊 

Again, sorry for being stubborn, hope you get the idea!

**Comment by yurist38** [comment] 2019-04-27 21:17
Thank you for explaining that, I got the idea. But it still sounds a bit weird to me, to be honest. I simply don't see any benefit of such an experiment. Maybe I don't understand something, but from my perspective, the project won't lose anything if you add the transpilation stage to it. Opposite, most likely the bundle size will be even smaller and the codebase will be more reliable and bullet-proof with TS. Both transpilation and build will be done automatically in CI pipelines anyway.

About the README you're right, it's better to mention that it needs to be compiled to ES5 because most of the projects are ignoring `node_modules` folder on transpilation.

**Comment by StrayFromThePath** [comment] 2019-05-15 14:07
Hey, @mcongy, I added type definitions to DefinitelyTyped. `npm install --save @types/wouter`

**Comment by molefrog** [comment] 2019-05-16 18:33
@StrayFromThePath Thanks a lot for the help, appreciate that. I have added a section in README covering the TypeScript support:
https://github.com/molefrog/wouter/blob/master/README.md#can-i-use-wouter-in-my-typescript-project

**Closed by molefrog** 2019-05-16 18:33 UTC
Labels: help wanted
